### ISSUE TITLE
colors doesnt get applied.

### ISSUE THREAD

**Issue by thepenguinthatwants** [losoliveirasilva/rofigen#1]
This script actually works quite well but the problem is that even adding typeset -A colors setup, it doesnt get applied. Colors are still based of the default rofi theme that I have.

Any clue whats causing this and how to fix?

**Comment by losoliveirasilva** [comment]
Maybe it's something related to a Rofi update, cause this script doesn't get touched in two years. I'll try to take a look this week, but feel free to make a PR if you find something.

**Comment by losoliveirasilva** [comment]
@thepenguinthatwants Rofi now supports themes, and that should be a better way to colorize it.
