### ISSUE TITLE
Spaces in filenames

### ISSUE THREAD

**Issue by Nmoleo64** [losoliveirasilva/rofigen#4]
If the path of the script I am passing to rofigen.sh has a space in it, the script breaks even if I use a backslash or double/single quotes to escape it.

The issue appears to be line  4 of rofigen: `source $1`

I replaced it with `source "$1"` and that fixed the issue for me,

**Comment by losoliveirasilva** [comment]
@Nmoleo64 Glad to hear that rofigen works for you. If you want, you can open a PR fixing this. Don't forget to mention this issue.

I'll close this cause you already solve it.
